In [1]:
import numpy as np
import pandas as pd

# For Song Lyrics:

In [2]:
first_decades = pd.read_csv('Billboard_Top_100_Data.csv')
first_decades = first_decades.drop(columns={'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'})
first_decades = first_decades[first_decades.Year >= 1960]

last_decade = pd.read_csv('billboardHot100_1999-2019.csv').dropna()
last_decade = last_decade.drop(columns={'Peak.position'}).merge(
    last_decade[['Artists', 'Name','Peak.position']].groupby(['Artists','Name']).min(), 
    on = ['Artists','Name'], how = 'left')

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (0,1,4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
cleaned_values = last_decade[last_decade.Year == 0]
for year in range(2013,2020):
    
    year_values = last_decade[last_decade.Year == year].sort_values(
        'Peak.position').drop_duplicates().reset_index(drop=True)
    cleaned_values = cleaned_values.append(year_values.loc[0:99,])
    
new_line = '\n'    
cleaned_values = cleaned_values.drop(columns={'Peak.position'}).rename(columns={
    'Artists':'Artist', 'Name':'Song Name'}).reset_index(drop=True)
cleaned_values.Year = cleaned_values.Year.astype(int)
cleaned_values['Lyrics'] = [s[s.find(new_line)+1:].replace(new_line,' ') for s in cleaned_values.Lyrics]

In [4]:
final_data = first_decades.append(cleaned_values).reset_index(drop=True)
final_data.to_pickle("song_data_all.pkl")

In [5]:
cleaned_values = last_decade[last_decade.Year == 0]
for year in range(2000,2020):
    
    year_values = last_decade[last_decade.Year == year].sort_values(
        'Peak.position').drop_duplicates().reset_index(drop=True)
    cleaned_values = cleaned_values.append(year_values.loc[0:99,])
    
new_line = '\n'    
cleaned_values = cleaned_values.drop(columns={'Peak.position'}).rename(columns={
    'Artists':'Artist', 'Name':'Song Name'}).reset_index(drop=True)

cleaned_values.Year = cleaned_values.Year.astype(int)
cleaned_values['Lyrics'] = [s[s.find(new_line)+1:].replace(new_line,' ') for s in cleaned_values.Lyrics]
cleaned_values

,Artist,Song Name,Year,Lyrics
0,matchbox twenty,Bent,2000,And if I fall along the way Pick me up and dus...
1,'N Sync,It's Gonna Be Me,2000,"It's gonna be me Oh, yeah You might've been hu..."
2,Enrique Iglesias,Be With You,2000,Monday night and I feel so low I count the hou...
3,Aaliyah,Try Again,2000,"It's been a long time, we shouldn't have left ..."
4,Janet,Doesn't Really Matter,2000,"Doesn't matter, doesn't matter Doesn't matter ..."
...,...,...,...,...
1995,FLETCHER,Undrunk,2019,Wish I could get a little un-drunk so I could ...
1996,Billie Eilish,Ilomilo,2019,Told you not to worry But maybe that's a lie H...
1997,Luke Combs,Even Though I'm Leaving,2019,"Daddy, I'm afraid, won't you stay a little whi..."
1998,"Lil Peep, iLoveMakonnen",I've Been Waiting,2019,"Whoa, yeah I've been waiting I've been waiting..."
1999,Iggy Azalea,Sally Walker,2019,"J White, I need a beat, I can go off on Ooh Li..."

In [6]:
cleaned_values.to_pickle("song_data_2000s.pkl")

# For reddit data

In [45]:
reddit_data = pd.read_csv('final_labels.csv')
reddit_data = reddit_data[['body', 'level_1', 'level_2', 'level_3','split']].reset_index(drop=True)
reddit_data

,body,level_1,level_2,level_3,split
0,Do you have the skin of a 80 year old grandma?...,Nonmisogynistic,None_of_the_categories,NaN,train
1,This is taking a grain of truth and extrapolat...,Nonmisogynistic,None_of_the_categories,NaN,train
2,Honestly my favorite thing about this is that ...,Nonmisogynistic,None_of_the_categories,NaN,test
3,Source? Doesnt sound right to me idk,Nonmisogynistic,None_of_the_categories,NaN,test
4,"Damn, I saw a movie in which the old woman bat...",Misogynistic,Derogation,Moral_inferiority,train
...,...,...,...,...,...
6562,Should I send my ex-boyfriends mom a thank you...,Misogynistic,Misogynistic_pejorative,NaN,test
6563,"1. Whatever vibration you put out, you will at...",Misogynistic,Misogynistic_pejorative,NaN,train
6564,"1. Whatever vibration you put out, you will at...",Misogynistic,Misogynistic_pejorative,NaN,train
6565,>Please keep in mind that just because YOU vie...,Misogynistic,Misogynistic_pejorative,NaN,train
6566,"Yes. I mean, given an example:\n\nRacist white...",Misogynistic,Misogynistic_pejorative,NaN,train

In [46]:
class_map = reddit_data[['level_1','level_2','level_3']].drop_duplicates(
                ).sort_values(['level_1','level_2','level_3']).reset_index(drop=True)
#class_map['new_class'] = ['Derogation-Discredit',
#                          'Derogation-Discredit',
#                          'Derogation-Discredit', 
#                          'Objectification-Stereotyping',
#                          'Non',
#                          'Derailing-Attacks',
#                          'Derailing-Attacks',
#                          'Derailing-Attacks',
#                          'Dominance',
#                          'Dominance',
#                          'Dominance',
#                          'Objectification-Stereotyping',
#                          'Threatening-Harassment',
#                          'Threatening-Harassment',
#                          'Threatening-Harassment',
#                          'Non',
#                          'Non',
#                          'Non',
#                          'Non',
#                          'Non']

class_map['new_class'] = ['Derogation',
                          'Derogation',
                          'Derogation', 
                          'Derogation',
                          'Non',
                          'Derogation',
                          'Derogation',
                          'Derogation',
                          'Treatment',
                          'Treatment',
                          'Treatment',
                          'Treatment',
                          'Treatment',
                          'Treatment',
                          'Treatment',
                          'Non',
                          'Non',
                          'Non',
                          'Non',
                          'Non']

reddit_data_class = reddit_data.merge(class_map, on=['level_1','level_2','level_3'], how='left')

class_map

,level_1,level_2,level_3,new_class
0,Misogynistic,Derogation,Intellectual_inferiority,Derogation
1,Misogynistic,Derogation,Moral_inferiority,Derogation
2,Misogynistic,Derogation,Other,Derogation
3,Misogynistic,Derogation,Sexual_or_physical_limitations,Derogation
4,Misogynistic,Misogynistic_pejorative,NaN,Non
5,Misogynistic,Misogynistic_personal_attack,Gender_of_recipient_is_Female,Derogation
6,Misogynistic,Misogynistic_personal_attack,Gender_of_recipient_is_Male,Derogation
7,Misogynistic,Misogynistic_personal_attack,Gender_of_recipient_is_Unknown,Derogation
8,Misogynistic,Treatment,Disrespectful_actions_Controlling,Treatment
9,Misogynistic,Treatment,Disrespectful_actions_Manipulation,Treatment
10,Misogynistic,Treatment,Disrespectful_actions_Other,Treatment
11,Misogynistic,Treatment,Disrespectful_actions_Seduction_and_conquest,Treatment
12,Misogynistic,Treatment,Threatening_Physical_violence,Treatment
13,Misogynistic,Treatment,Threatening_Privacy,Treatment
14,Misogynistic,Treatment,Threatening_Sexual_violence,Treatment
15,Nonmisogynistic,Counter_speech,NaN,Non
16,Nonmisogynistic,None_of_the_categories,NaN,Non
17,Nonmisogynistic,Nonmisogynistic_personal_attack,Gender_of_recipient_is_Female,Non
18,Nonmisogynistic,Nonmisogynistic_personal_attack,Gender_of_recipient_is_Male,Non
19,Nonmisogynistic,Nonmisogynistic_personal_attack,Gender_of_recipient_is_Unknown,Non

In [47]:
# drop duplicates here is for multiple perjoratives in one bit of text
reddit_data_class = reddit_data_class.drop_duplicates().reset_index(drop=True)

In [48]:
# still a few duplicates to get rid of...first, some data put in train and test, we will put just in train
reddit_data_clean_1 = reddit_data_class[['body', 'new_class', 'split']].drop_duplicates()
reddit_data_clean_1 = reddit_data_clean_1.merge(reddit_data_clean_1[['body','split']].drop_duplicates(
                        ).groupby(['body']).count().rename(columns={'split':'count'}), on=['body'],how='left')
reddit_data_clean_1 = reddit_data_clean_1[(reddit_data_clean_1['count'] == 1) | 
                                          (reddit_data_clean_1.split == 'train')].reset_index(drop=True)

In [49]:
# some more duplicate labels to clean:
reddit_data_clean_2 = reddit_data_clean_1[['body', 'new_class', 'split']]
reddit_data_clean_2 = reddit_data_clean_2.merge(reddit_data_clean_2[['body','new_class']].drop_duplicates(
                        ).groupby(['body']).count().rename(columns={'new_class':'count'}), on=['body'],how='left')
reddit_data_clean_2 = reddit_data_clean_2[(reddit_data_clean_2['count'] == 1) | 
                                          (reddit_data_clean_2.new_class != 'Non')].reset_index(drop=True)

In [50]:
# now have final data
final_reddit = reddit_data_clean_2[['body', 'new_class', 'split']].drop_duplicates()
final_reddit['body'] = [" ".join(filter(lambda x:x[0:4]!='http', a.split())) for a in final_reddit['body']]
final_reddit

                                                   body   new_class  split
0     Do you have the skin of a 80 year old grandma?...         Non  train
1     This is taking a grain of truth and extrapolat...         Non  train
2     Honestly my favorite thing about this is that ...         Non   test
3                  Source? Doesnt sound right to me idk         Non   test
4     Damn, I saw a movie in which the old woman bat...  Derogation  train
...                                                 ...         ...    ...
6160                              FDS Level Up Bitches!         Non  train
6161  It seems like you're taking on the masculine r...         Non   test
6162  Should I send my ex-boyfriends mom a thank you...         Non   test
6163  >Please keep in mind that just because YOU vie...         Non  train
6164  Yes. I mean, given an example: Racist white wo...         Non  train

[6165 rows x 3 columns]

In [51]:
final_reddit.to_pickle("reddit_labels.pkl")

# For twitter data

In [38]:
twitter_training = pd.read_csv('en_training.tsv', sep='\t')
twitter_training['split'] = 'train'
twitter_test = pd.read_csv('en_testing.tsv', sep='\t')
twitter_test['split'] = 'test'
twitter_data = twitter_training.append(twitter_test)
twitter_data

,id,text,misogynous,misogyny_category,target,split
0,1,Please tell me why the bitch next to me in the...,1,dominance,active,train
1,2,@emmasharp003 @Ldrake48Lee Bitch shut the fuck up,1,dominance,active,train
2,3,"@abzdafab Dear cunt, please shut the fuck up.",1,dominance,active,train
3,4,RT @queenofdragonsb: Pls shut the fuck up bitch,1,dominance,active,train
4,5,"RT @21bIvck: ""when u gonna get your license"" S...",1,dominance,active,train
...,...,...,...,...,...,...
995,5064,@ananavarro You people are hysterical. Dow up ...,0,0,0,test
996,5065,@ChrisCuomo @NewDay you leftist gimps are hyst...,0,0,0,test
997,5066,@shornawx_ @WoleOdeleye 10 year old you is hys...,0,0,0,test
998,5067,@JayteKz Tekashi a whole bitch lol fuck that n...,0,0,0,test
999,5068,@realDonaldTrump @NFL This is hysterical. Itâ€™s...,0,0,0,test

In [39]:
class_map = twitter_data[['misogynous', 'misogyny_category', 'target']].drop_duplicates(
                ).sort_values(['misogyny_category','target']).reset_index(drop=True)

#class_map['new_class'] = ['Dominance',
#                          'Dominance',
#                          'Threatening-Harassment', 
#                          'Derailing-Attacks',
#                          'Derogation-Discredit',
#                          'Derogation-Discredit',
#                          'Threatening-Harassment',
#                          'Objectification-Stereotyping',
#                          'Objectification-Stereotyping',
#                          'Derailing-Attacks',
#                          'Non']

class_map['new_class'] = ['Non',
                          'Derogation',
                          'Derogation', 
                          'Derogation',
                          'Derogation',
                          'Treatment',
                          'Treatment',
                          'Treatment',
                          'Treatment',
                          'Derogation',
                          'Derogation']

twitter_data_class = twitter_data.merge(class_map, on=['misogynous', 'misogyny_category', 'target'], how='left')

class_map

    misogynous  misogyny_category   target   new_class
0            0                  0        0         Non
1            1          derailing   active  Derogation
2            1          derailing  passive  Derogation
3            1          discredit   active  Derogation
4            1          discredit  passive  Derogation
5            1          dominance   active   Treatment
6            1          dominance  passive   Treatment
7            1  sexual_harassment   active   Treatment
8            1  sexual_harassment  passive   Treatment
9            1         stereotype   active  Derogation
10           1         stereotype  passive  Derogation

In [40]:
twitter_data_class['body'] = [" ".join(filter(lambda x:x[0:2]!='RT', a.split())) for a in twitter_data_class['text']]
twitter_data_class['body'] = [" ".join(filter(lambda x:x[0]!='@', a.split())) for a in twitter_data_class['body']]
twitter_data_class['body'] = [" ".join(filter(lambda x:x[0:4]!='http', a.split())) for a in twitter_data_class['body']]
twitter_data_clean = twitter_data_class[['body', 'new_class', 'split']]
twitter_data_clean['Misogyny'] = [1 if i != 'Non' else 0 for i in twitter_data_clean.new_class]

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

In [43]:
twitter_data_clean.to_pickle("twitter_labels.pkl")